In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
x = np.array([1,2,3,4,5,6,7,])
print(x)
print(type(x))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [11]:
y= [1,2,3,4,5,6,7]
print(y)
print(type(y))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [12]:
%timeit [j**4 for j in range (1,9)]

1.97 µs ± 267 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
import numpy as np

%timeit np.arange(1,9)**4

1.37 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating NumPy Arrays

In [19]:
import numpy as np

x =[3,5,7,9,1,4,7,8,9]

y = np.array(x)

y

array([3, 5, 7, 9, 1, 4, 7, 8, 9])

In [22]:
l = []

for i in range(1,6):
    x = int(input("Enter: "))
    l.append(x)
    
print(np.array(l))

Enter: 24
Enter: 4
Enter: 5
Enter: 6
Enter: 65
[24  4  5  6 65]


# Types Of Array

In [25]:
x =[3,5,7,9,1,4,7,8,9]

y = np.array(x)

y

print(y.ndim)

1


In [26]:
l2 = np.array([[1,2,3,4],[2,3,4,5]])#both list are same numbers

In [39]:
print(l2)

print(l2.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2


In [40]:
l3 = np.array([[[1,2,3,4],[3,4,5,6],[6,7,8,9]]])

print(l3)
print(l3.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [6 7 8 9]]]
3


In [41]:
ln = np.array([1,2,3,4],ndmin = 10)#No of dimension array

print(ln)
print(ln.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special types of Array

# 1.ZERO

In [43]:
import numpy as np

ar_zero = np.zeros(4)
ar_zeros1 = np.zeros((3,4))

print(ar_zero)
print(ar_zeros1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2.ONES

In [44]:
ar_1 = np.ones(4)

print(ar_1)

[1. 1. 1. 1.]


# 3.EMPTY

In [45]:
ar_em = np.empty(4)

print(ar_em)#privious element create

[1. 1. 1. 1.]


# 4.RANGE

In [46]:
ar_rn = np.arange(5)

print(ar_rn)

[0 1 2 3 4]


# 5.DIAGONAL ELEMENT

# ar_dia = np.eye(5)

print(ar_dia)

In [51]:
ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# 6.Linspacing

In [55]:
ar_lin = np.linspace(0,40,num=6)

print(ar_lin)

[ 0.  8. 16. 24. 32. 40.]


# *Creating Random Numbers Numpy Array

# 1.rand()

In [4]:
import numpy as np  #One Dimension

var = np.random.rand(6)
print(var)

[0.60140654 0.94269211 0.24676487 0.96488981 0.26267631 0.99293543]


In [6]:
var = np.random.rand(2,6)#Two Dimension

print(var)
print(var.ndim)

[[0.89874393 0.02991444 0.71694817 0.38005449 0.60045815 0.31653545]
 [0.98379772 0.87612096 0.96315974 0.70684202 0.54616888 0.00313724]]
2


# 2.randn()

In [11]:
var2 = np.random.randn(8)    #random number may be positive or Negative

print(var2)

[-0.46594145  0.95840388  0.21940256 -0.20309601 -0.82027383 -0.15885394
 -0.81417649  0.0150544 ]


# 3.ranf()

In [15]:
import numpy as np   #close t0 zero [o.o,1,0] but no 1 including

var3 = np.random.ranf(8)

print(var3)

[0.92954014 0.00758456 0.60555227 0.29850523 0.88583778 0.82106334
 0.98184644 0.73150028]


# 4.randint()

In [31]:
import numpy as np     #random number between two numbers

var4 = np.random.randint(0,45)

print(var4)

29


# Data Types NumPy Array

In [33]:
import numpy as np

var = np.array([1,2,3,4,5,6,7,8,9,45,56,67,78,78,65,4,33,3,3,3,3,3,99])

print("Data Type : ", var.dtype)

Data Type :  int32


In [34]:
import numpy as np

var = np.array([1.34,2.45,3.54,4.56,9.56])

print("Data Type : ", var.dtype)

Data Type :  float64


In [35]:
var = np.array(["A","B","C","D","E"])

print("Data Type : ", var.dtype)

Data Type :  <U1


In [38]:
var = np.array(["A","B",1.34,2.45,3.54,4.56,9.56])

print("Data Type : ", var.dtype)

Data Type :  <U32


In [40]:
var = np.array([1,2,3,4,5,6,7,8,9,45,56,67,78,78,65,4,33,3,3,3,3,3,99],dtype = np.int8)

print("Data Type : ", var.dtype)
print(var)

Data Type :  int8
[ 1  2  3  4  5  6  7  8  9 45 56 67 78 78 65  4 33  3  3  3  3  3 99]


In [42]:
var = np.array([1,2,3,4,5,6,7,8,9,45,56,67,78,78,65,4,33,3,3,3,3,3,99], dtype = "f")

print("Data Type : ", var.dtype)
print(var)

Data Type :  float32
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 45. 56. 67. 78. 78. 65.  4. 33.  3.
  3.  3.  3.  3. 99.]


In [46]:
var = np.array([1,2,3,4,5,6,7,8,9,45,56,67,78,78,65,4,33,3,3,3,3,3,99])

new = np.float32(var)

new1 = np.int_(new)


print("Data Type : ", var.dtype)
print("Data Type : ", new.dtype)
print("Data Type : ", new1.dtype)
print(var)
print(new1)
print(new)

Data Type :  int32
Data Type :  float32
Data Type :  int32
[ 1  2  3  4  5  6  7  8  9 45 56 67 78 78 65  4 33  3  3  3  3  3 99]
[ 1  2  3  4  5  6  7  8  9 45 56 67 78 78 65  4 33  3  3  3  3  3 99]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 45. 56. 67. 78. 78. 65.  4. 33.  3.
  3.  3.  3.  3. 99.]


In [47]:
x3 = np.array([1,2,3,4,5])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


# Shape and Reshaping

# 1.Shape

In [50]:
import numpy as np 

var = np.array([[1,2,4],[2,3,6]])

print(var)
print()
print(var.shape)

[[1 2 4]
 [2 3 6]]

(2, 3)


In [54]:
var1 = np.array([2,3,4,5], ndmin=10)

print(var1)
print(var1.ndim)
print(var1.shape)

[[[[[[[[[[2 3 4 5]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


# Reshape


In [68]:
import numpy as np

var = np.array([1,2,3,4,5,6,8,9,4,3,2,3])

x = var.reshape(4,3)

x2 = x.T

print(x)
print(x.ndim)
print(x2)
print(x2.ndim)

one = x.reshape(-1)
print(one)
print(one.ndim)

[[1 2 3]
 [4 5 6]
 [8 9 4]
 [3 2 3]]
2
[[1 4 8 3]
 [2 5 9 2]
 [3 6 4 3]]
2
[1 2 3 4 5 6 8 9 4 3 2 3]
1


# Arithmatic Operation In Numpy Array

# 1D Array

In [75]:
import numpy as np

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.add(var1,5)
print(varadd)


[ 7  8  9 10 11 12]


In [76]:

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.subtract(var1,5)
print(varadd)

[-3 -2 -1  0  1  2]


In [77]:

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.divide(var1,5)
print(varadd)

[0.4 0.6 0.8 1.  1.2 1.4]


In [78]:

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.multiply(var1,5)
print(varadd)

[10 15 20 25 30 35]


In [79]:

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.mod(var1,5)
print(varadd)

[2 3 4 0 1 2]


In [82]:

var1 = np.array([2,3,4,5,6,7])
var2 = np.array([3,4,5,6,7,8])

varadd = np.reciprocal(var2)
print(varadd)

[0 0 0 0 0 0]


# 2D Array

In [85]:
var1 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])
var2 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])

varadd = np.add(var1,var2)
print(varadd)



[[ 4  6  8 10 12 14]
 [ 6  8 10 12 14 16]]


In [86]:
var1 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])
var2 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])

varadd = np.reciprocal(var1)
print(varadd)


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [88]:
var1 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])
var2 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])

varadd = np.subtract(var1,var2)
print(varadd)


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [89]:
var1 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])
var2 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])

varadd = np.multiply(var1,var2)
print(varadd)


[[ 4  9 16 25 36 49]
 [ 9 16 25 36 49 64]]


In [90]:
var1 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])
var2 = np.array([[2,3,4,5,6,7],[3,4,5,6,7,8]])

varadd = np.divide(var1,var2)
print(varadd)


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# Arithmetic Functions


In [7]:
import numpy as np   #one dimension

var = np.array([4,34,2,3,4,5,6,7])

print("min: ",np.min(var),np.argmin(var))

print("max: ",np.max(var), np.argmax(var))

print("sqrt: ",np.sqrt(var))

min:  2 2
max:  34 1
sqrt:  [2.         5.83095189 1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131]


In [6]:
var1 = np.array([[2,1,3],[9,5,6]]) #tw0 dimension

print(np.min(var1,axis=0))

[2 1 3]


In [10]:
var2  = np.array([1,2,3,4,5,6,7,8,9,6])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026  0.96017029]
[ 1  3  6 10 15 21 28 36 45 51]


# Broadcasting NumPy Arrays

In [12]:
import numpy as np

var1 = np.array([1,2,3,4])

var2 = np.array([5,6,7,8])

print(var1 + var2)

[ 6  8 10 12]


In [17]:
var1 = np.array([1,2,3,4])

var2 = np.array([[5],[6],[7],[8]])

print(var1)
print()
print(var1.shape)
print()
print(var2)
print()
print(var2.shape)
print()
print(var1 + var2)

[1 2 3]

(3,)

[[5]
 [6]
 [7]
 [8]]

(4, 1)

[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]


# Indexing and Slicing

# indexing

In [20]:
import numpy as np

var = np.array([7,8,9,6])

print(var[1])
print(var[-2])

8
9


In [26]:
var1 = np.array([[1,2,3],[4,6,5]])  #Got number in array 2D
print(var1)

print(var1.ndim)

print(var1[0,2])

[[1 2 3]
 [4 6 5]]
2
3


In [33]:
var2 = np.array([[[1,2,3],[2,3,4],[5,6,7]]])  #Got number in array 3D

print(var2)

print(var2.ndim)

print(var2[0,2,1])

[[[1 2 3]
  [2 3 4]
  [5 6 7]]]
3
6


# Slicing

In [45]:
import numpy as np 

var = np.array([4,5,6,7,8,9])    #For One Dimension 
#               0,1,2,3,4,5

print(var)
print()

print(var.ndim)
print()

print("5 To End : ",var[1:])

print()

print("Start to 8:",var[:5])

print("Start to End:",var[1:3:1])



[4 5 6 7 8 9]

1

5 To End :  [5 6 7 8 9]

Start to 8: [4 5 6 7 8]
Start to End: [5 6]


In [52]:
var2 = np.array([[2,3,4,5,6,7,8],[4,5,6,4,5,6,6]])   # For Two Dimension 

print(var2)
print()
print(var2.ndim)
print()
print("3 to 7: ",var2[1,2:6])



[[2 3 4 5 6 7 8]
 [4 5 6 4 5 6 6]]

2

3 to 7:  [6 4 5 6]


In [54]:
var3 = np.array([[[2,3,4,5,6,7],[6,6,7,8,5,3],[3,4,5,6,7,8]]])  #for Three Dimension

print(var3)
print()
print(var3.ndim)
print()
print("4 To 7: ",var3[0,2,1:5])

[[[2 3 4 5 6 7]
  [6 6 7 8 5 3]
  [3 4 5 6 7 8]]]

3

4 To 7:  [4 5 6 7]


# Iterating NumPy Arrays

In [58]:
import numpy as np

var = np.array([4,7,8,9,6,5,4,4,3,2,1])

print(var)
print()

for i in var :
    print(i)
    

[4 7 8 9 6 5 4 4 3 2 1]

4
7
8
9
6
5
4
4
3
2
1


In [60]:
var2 = np.array([[2,3,4,5,6],[4,5,6,7,5]])

print(var2)
print()
print(var2.ndim)
print()
for j in var2 :
    print(j)
    
print()
for k in var2 :
    for l in k :
        print(l)

[[2 3 4 5 6]
 [4 5 6 7 5]]

2

[2 3 4 5 6]
[4 5 6 7 5]

2
3
4
5
6
4
5
6
7
5


In [62]:
var3 = np.array([[[1,2,3,4],[2,3,4,5],[4,6,7,8]]])

print(var3)
print()
print(var3.ndim)
print()

for i in var3 :
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [2 3 4 5]
  [4 6 7 8]]]

3

1
2
3
4
2
3
4
5
4
6
7
8


In [67]:
var3 = np.array([[[1,2,3,4],[2,3,4,5],[4,6,7,8]]]) #Using nditer function iterate values
print(var3)
print()
print(var3.ndim)
print()

for i in np.nditer(var3,flags=['buffered'],op_dtypes=[float]): #convert in data types
    print(i)
    

[[[1 2 3 4]
  [2 3 4 5]
  [4 6 7 8]]]

3

1.0
2.0
3.0
4.0
2.0
3.0
4.0
5.0
4.0
6.0
7.0
8.0


In [69]:
var4 = np.array([[[1,2,3,4],[2,3,4,5],[4,6,7,8]]])#check indexing 
print(var4)
print()
print(var4.ndim)
print()

for i,d in np.ndenumerate(var4):
    print(i,d)


[[[1 2 3 4]
  [2 3 4 5]
  [4 6 7 8]]]

3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 2
(0, 1, 1) 3
(0, 1, 2) 4
(0, 1, 3) 5
(0, 2, 0) 4
(0, 2, 1) 6
(0, 2, 2) 7
(0, 2, 3) 8


# Copy & View in NumPy Array

In [73]:
import numpy as np

var = np.array([2,4,6,8,9,6])#Copy

co = var.copy()
var[2]=56
print(var)
print("Copy :",co)

[ 2  4 56  8  9  6]
Copy : [2 4 6 8 9 6]


In [74]:

var = np.array([2,4,6,8,9,6])#View

vi = var.view()
var[2]=56
print(var)
print("View:",vi)

[ 2  4 56  8  9  6]
View: [ 2  4 56  8  9  6]


# Join and Split in Numpy Array

# JOIN

In [76]:
import numpy as np

var1 = np.array([2,3,4,5])   #For One Dimension
var2 = np.array([5,6,7,8])

ar_new = np.concatenate((var1,var2))
print(ar_new)

[2 3 4 5 5 6 7 8]


In [80]:
import numpy as np

var1 = np.array([[2,3],[4,5]])   #For Two Dimension
var2 = np.array([[5,6],[7,8]])

ar_new1 = np.concatenate((var1,var2),axis=1)

print(ar_new1)
print(var1)
print(var1.ndim)

print(var2)
print(var2.ndim)

[[2 3 5 6]
 [4 5 7 8]]
[[2 3]
 [4 5]]
2
[[5 6]
 [7 8]]
2


In [87]:
var1 = np.array([2,3,4,5])   #USE  STACK FUNCTION
var2 = np.array([5,6,7,8])
ar_new1 = np.stack((var1,var2),axis=0)
ar_new2 = np.dstack((var1,var2))#height
ar_new3 = np.hstack((var1,var2))#row
ar_new4 = np.vstack((var1,var2))#column
print(ar_new1)
print()
print(ar_new2)
print()
print(ar_new3)
print()
print(ar_new4)

[[2 3 4 5]
 [5 6 7 8]]

[[[2 5]
  [3 6]
  [4 7]
  [5 8]]]

[2 3 4 5 5 6 7 8]

[[2 3 4 5]
 [5 6 7 8]]


# Split

In [88]:
import numpy as np

var = np.array([3,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print(ar)
print(type(ar))

[3 3 4 5 6]
[array([3, 3]), array([4, 5]), array([6])]
<class 'list'>


In [91]:
var = np.array([[3,3],[4,5],[6,8]])

print(var)
print(var.ndim)

ar = np.array_split(var,3)

print(ar)

[[3 3]
 [4 5]
 [6 8]]
2
[array([[3, 3]]), array([[4, 5]]), array([[6, 8]])]


# NumPy Array Functions

#SORT,SEARCH,SORTED,FILTER

# Search

In [94]:
import numpy as np

var = np.array([2,3,4,5,6,7,8,9,2,3,4,5,62,3,2,3,42,3,4,2,3,2])

x= np.where(var%2 == 4)
print(x)

(array([], dtype=int64),)


# SearchSorted

In [95]:
var = np.array([2,3,4,5,6,7,8,9,2,3,4,5,62,3,2,3,42,3,4,2,3,2])

x= np.searchsorted(var, 4)

print(x)

2


# Sort

In [96]:
var_1 = np.array([2,3,4,5,6,7,8])

print(np.sort(var_1))

[2 3 4 5 6 7 8]


# Filter Array

In [98]:
var_1 = np.array([2,3,4,5])

f = [True,False,False,True]

new_a = var_1[f]
print(new_a)

[2 5]


# Arithmetic Function 
Shuffle
Unique
Resize
Flatten
Revel


# Shuffle

In [2]:
import numpy as np 

var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 1 3 5 4]


# Unique

In [105]:
var = np.array([1,2,3,4,5,2,3,2,3,4,5,2,3,2,3])

x = np.unique(var,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4], dtype=int64), array([1, 5, 5, 2, 2], dtype=int64))


# Resize

In [5]:
var = np.array([1,2,3,4,5,6])

y= np.resize(var,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten

In [8]:
import numpy as np

var = np.array([[2,3,4,5],[3,4,5,6]])
print(var)
print(var.ndim)

print(var.flatten())

[[2 3 4 5]
 [3 4 5 6]]
2
[2 3 4 5 3 4 5 6]


In [14]:
var = np.array([[2,3,4,5],[3,4,5,6]])
print(var)
print(var.ndim)

print(var.flatten(order="F")) #flatten
print(var.flatten(order="C"))
print()
print()
var2 = np.ravel(y,order="K")#Ravel
print(var2)


[[2 3 4 5]
 [3 4 5 6]]
2
[2 3 3 4 4 5 5 6]
[2 3 4 5 3 4 5 6]


[1 2 3 4 5 6]


# Insert and Delete Function

# 1.Insert


In [19]:
import numpy as np

var = np.array([4,5,6,7,8,9,0])
print(var)
print(var.ndim)
print(var.dtype)
print(type(var))
print()

v= np.insert(var , (3,5) , 4.5)#accept only in int format
print(v)


[4 5 6 7 8 9 0]
1
int32
<class 'numpy.ndarray'>

[4 5 6 4 7 8 4 9 0]


In [32]:
#for two dimension


var= np.array([[3,5,6],[5,6,7]])
v = np.insert(var ,2, [2,6,3], axis=0)
print(v)
print()
x = np.append(var,6.5)
print(x)
print()

y = np.append(var,[[45,44,32]],axis=0)
print(y)

[[3 5 6]
 [5 6 7]
 [2 6 3]]

[3.  5.  6.  5.  6.  7.  6.5]

[[ 3  5  6]
 [ 5  6  7]
 [45 44 32]]


# 2.Delete

In [33]:
import numpy as np 

var= np.array([3,4,5,6,7])

print(var)
d= np.delete(var,3)
print(d)
    

[3 4 5 6 7]
[3 4 5 7]


# Numpy Matrix

In [40]:
import numpy as np

var = np.matrix([[1,2],[3,4]])
var2= np.matrix([[1,2],[3,4]])

print(var)
print(type(var))
print(var*var2)
print(var.dot(var2))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [41]:
var1 = np.array([[1,2,3],[3,4,5]])

print(var1)
print(type(var1))



[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>


# Matrix Functions

In [ ]:
# Transpose
#swapaxes
#ainverse
#power
#Determinate

In [48]:
#1.Transpose

import numpy as np
 
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))
print()
print(var.T)
print()
print()

#2.Swapaxes
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [50]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.swapaxes(var3,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [51]:
#3.Inverse

var4 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var4))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [58]:
#4. Power



var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.matrix_power(var5,2))
print()

print(np.linalg.matrix_power(var5,0))
print()

print(np.linalg.matrix_power(var5,-3))





[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[-14.75    6.75 ]
 [ 10.125  -4.625]]


In [60]:
#5.Determinate 



var6 = np.matrix([[1,2,3],[1,3,4],[1,2,3]])
print(var6)
print()
print(np.linalg.det(var6))


[[1 2 3]
 [1 3 4]
 [1 2 3]]

0.0


In [ ]:
#######Thanks#########